# Generated by Django 4.1.6 on 2023-04-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
    ]
